### PR TITLE
fix can't select file name contains ' (U+0027)

### PR DESCRIPTION
**Pull request by bllli**

### CODE REVIEW

**Comment by sehmaschine** [comment]
not sure about this ...

isn't it better to use normalize instead?
see https://django-filebrowser.readthedocs.io/en/latest/settings.html#normalize-filename

**Comment by bllli** [comment]
Nope... I use django-filebrowser for view and select files stored on the server, so I won't upload them

**Comment by sehmaschine** [comment]
I just tried with a variety of special characters and I could not reproduce this. I have no issues selecting a file with TinyMCE (I assume you are referring to this since you did not specify what you mean with "selecting"). Before merging this I would like to be able to reproduce the issue ...

**Comment by sehmaschine** [comment]
Closing this for now since I'm not able to reproduce the issue and no further comment has been given.

**Pull request closed without merging**
