### PR TITLE
Testing improvements

### PR DESCRIPTION
**Pull request by adamrt**
As requested I've moved the request to stable/3.6.x - https://github.com/sehmaschine/django-filebrowser/pull/288

I will also close that request.

This is now at a stable position to merge. All tests have been updated, isolated, simplified. There is still work to be done, but this is a great point in which to share the tests. I've also updated the documentation as requested, by removing the virtualenv and changing it to a note.

Please let me know if you have any questions or concerns. Also, just check out this branch locally on your machine and run the tests. 

Thanks

### CODE REVIEW

**Comment by sehmaschine** [comment]
thanks – what an effort! I'll take a look at these asap and merge with master if all tests pass with my setup.

**Comment by sehmaschine** [comment]
@adamrt I'm probably missing something here, but ```python manage.py test filebrowser``` does not work anymore. any idea?

**Comment by sehmaschine** [comment]
@adamrt I've solved the issue mentioned before, but all tests are throwing errors (I'm not even close to figure out what's going on). Let's start with this: Are you creating a folder "folder" within the filebrowser DIRECTORY? If yes, do you think that's a good idea?

**Comment by sehmaschine** [comment]
@adamrt alright, I've solved most of the issue ... but I still had troubles when running the tests without tox (with using tox, everything's fine with my setup). So, I'm not sure if using ```python runtests.py``` is supposed to work. Should we even mention that option with the docs?

**Comment by adamrt** [comment]
Hey sorry for the late reply. One of the major changes was to no longer run the tests against a production or development project but to run it in isolation using a basic project as recommended by the django project.

Are you running these tests in the context of a django project or using the projects included with the tests?

If I download the master branch and install the dependencies (django, pillow, grappelli, mock) and do python runtests.py it runs for me.

Thanks for taking the time to look at this!

**Comment by sehmaschine** [comment]
@adamrt it works now. I am not able to install the requirements with my virtualenv (I'm using tox instead in order to build a separate virtualenv for testing). besides, I had to do some updates (esp. because of stdout and python3). see https://travis-ci.org/sehmaschine/django-filebrowser

**Comment by adamrt** [comment]
Ok good. The only reason I put the stdout lines in there was to hide them from testing output. It was only cosmetic so removing them is the correct call.

Are there any other issues or things I can help clean up right now? I still plan on adding and splitting out the tests more. Like unit testing the methods in isolation, etc.

**Comment by sehmaschine** [comment]
@adamrt I think we're fine for now. If you work on further improvements, you might wanna think about a separate folder for the test project instead of using "tests" (but that's up to you).

**Comment by adamrt** [comment]
Hey @sehmaschine,

The `tests` folder isn't for the test project specifically. It's actually that the `tests` folder contains all the tests and there is just a `settings.py` and `urls.py` to give a basic project.

This is a common practice in the django community from what I've seen.

**Pull request merged**
