### PR TITLE
Testing improvements

### PR DESCRIPTION
**Pull request by adamrt**
I've always had some difficulty making changes to filebrowser because I couldn't test properly. I've rewritten and simplified much of the testing infrastructure. While I made many large changes, I tried to keep the commits broken up and obvious. 

I would like to continue with this work but I've reached a good stopping point and want to make sure you approve of the changes I'm making before I continue.

One major change is that I've included a basic django project (just urs.py and settings.py) to test against instead of testing against production. I think this is much safer and easier to test in isolation. I have not done this for test_sites.py yet, but would be happy to do that work. 

test_settings.py I believe should be moved to the django check framework.

I updated the testing documentation with the basics.

Please let me know if you have any questions or recommendations. I would be happy to continue this work.

### CODE REVIEW

**Comment by sehmaschine** [comment]
wow ... what an effort. thanks!

Some thoughts on this (please note that I just roughly checked the code):

* I'm not sure about the virtualenv. do we really need that?
* About test_sites.py: We currently test each deployed filebrowser site, which seems unnecessary from my point of view. It's probably better to use a specific test_site instead. This would probably simplify some tests as well.

you might wanna take a look at this pull-request for grappelli (https://github.com/sehmaschine/django-grappelli/pull/656) for some additional inspiration.

**Comment by adamrt** [comment]
Thanks for the reply.

1. Virtualenv is completely optional, just recommended since we would install a few packages for testing. I will make a note in the documentation.

2. Exactly! That is what I would like to do. I wanted to make it clear that using a test project/site was my intention before continuing all that work.

How would you like to proceed? Should this be committed and then I can do a few more large pull requests or would you prefer just one massive one that I keep adding to (ie. this one)? I prefer the former, but I'll open to either.

**Comment by sehmaschine** [comment]
I'll add a separate branch (testing) and you could add your pull-requests with that one. Ok?

**Comment by adamrt** [comment]
The only file I have left to update to the new style is test_sites. After that there is a very solid testing base in place. After that I think there are plenty of other things to add on top (tox, more coverage, renaming, rearanging, etc).

Would it make sense for me to finish up test_sites in this branch so that it can be merged into master then the new testing branch can be based off that so other people can utilize the tests. 

The reason I ask is I have additional changes for filebrowser I would like to make, but I want the testing in place before I start mucking about, but its much easier to understand pull-requests for branches based off master I think.

Just a thought

**Comment by sehmaschine** [comment]
It depends on how stable the new testing stuff is ... if you think it's fine to use master, I'm ok with that. But please note that master shouldn't break. So, basically your decision.

**Comment by adamrt** [comment]
Thats how I like to roll too (not breaking master). Let me finish test_sites and review, but I believe if you look at the commits they actually simplify and stabilize what was already there.  Famous last words I know, but I've always had an issue running the tests for filebrowser previously. 

Thanks and I'll push the additional changes this week

**Comment by sehmaschine** [comment]
you could use branch stable/3.6.x (currently equal to master) for the pull-request.

**Comment by adamrt** [comment]
Moving request to stable/3.6.x https://github.com/sehmaschine/django-filebrowser/pull/292

**Pull request closed without merging**
